In [1]:
import pandas as pd
# Creating a dictionary with intentionally messy data
data = {
 'StudentID': [101, 102, 103, 104, 101, 105, 106],
 'Name': ['Ali', 'Aisha', 'Chong', 'Muthu', 'Ali ', 'Siti', 'John'],
 'Score': [85, 92, 450, 78, 85, -15, 88], # Notice the impossible scores!
 'Grade': ['A', 'A', 'A+', 'B', 'A', 'F', 'a'] # Inconsistent casing ('a' vs 'A')
}
# Convert the dictionary into a Pandas DataFrame
df_messy = pd.DataFrame(data)
print("Here is our messy dataset:")
display(df_messy)

Here is our messy dataset:

   StudentID   Name  Score Grade
0        101    Ali     85     A
1        102  Aisha     92     A
2        103  Chong    450    A+
3        104  Muthu     78     B
4        101   Ali      85     A
5        105   Siti    -15     F
6        106   John     88     a

In [2]:
# Count how many duplicate rows exist
print("Number of duplicate rows:", df_messy.duplicated().sum())
# Show exactly which row is the duplicate so we can verify it
print("\nLook at the duplicate row:")
display(df_messy[df_messy.duplicated()])
# Drop the duplicate and save the result as a new table
df_deduped = df_messy.drop_duplicates()
print("\nDuplicates removed!")

Number of duplicate rows: 0

Look at the duplicate row:

Empty DataFrame
Columns: [StudentID, Name, Score, Grade]
Index: []

Duplicates removed!

In [3]:
# Filter the table to keep ONLY logical scores (between 0 and 100).
# The '&' means AND. Both conditions must be true!
# We add .copy() at the end to tell Pandas to make a fresh, independent table.
df_logical = df_deduped[(df_deduped['Score'] >= 0) & (df_deduped['Score'] <= 100)].copy()
print("Dataset after removing impossible scores:")
display(df_logical)

Dataset after removing impossible scores:

   StudentID   Name  Score Grade
0        101    Ali     85     A
1        102  Aisha     92     A
3        104  Muthu     78     B
4        101   Ali      85     A
6        106   John     88     a

In [4]:
# 1. Strip extra invisible whitespace from Names ('Ali ' becomes 'Ali')
df_logical['Name'] = df_logical['Name'].str.strip()
# 2. Convert all Grades to UPPERCASE ('a' becomes 'A')
df_logical['Grade'] = df_logical['Grade'].str.upper()
print("Final Cleaned Dataset:")
display(df_logical)

Final Cleaned Dataset:

   StudentID   Name  Score Grade
0        101    Ali     85     A
1        102  Aisha     92     A
3        104  Muthu     78     B
4        101    Ali     85     A
6        106   John     88     A